/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lesson = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'quiz' : IDL.Record({
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  }),
  'description' : IDL.Text,
  'starterCode' : IDL.Text,
  'solutionPattern' : IDL.Text,
});
export const Module = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
});
export const UserProgress = IDL.Record({
  'quizScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'completedLessons' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
  'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
  'markLessonComplete' : IDL.Func([IDL.Text], [], []),
  'resetProgress' : IDL.Func([], [], []),
  'submitQuizAnswer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lesson = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'quiz' : IDL.Record({
      'question' : IDL.Text,
      'correctIndex' : IDL.Nat,
      'options' : IDL.Vec(IDL.Text),
    }),
    'description' : IDL.Text,
    'starterCode' : IDL.Text,
    'solutionPattern' : IDL.Text,
  });
  const Module = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
  });
  const UserProgress = IDL.Record({
    'quizScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'completedLessons' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
    'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
    'markLessonComplete' : IDL.Func([IDL.Text], [], []),
    'resetProgress' : IDL.Func([], [], []),
    'submitQuizAnswer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };