/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lesson {
  'id' : string,
  'title' : string,
  'quiz' : {
    'question' : string,
    'correctIndex' : bigint,
    'options' : Array<string>,
  },
  'description' : string,
  'starterCode' : string,
  'solutionPattern' : string,
}
export interface Module {
  'id' : string,
  'name' : string,
  'lessons' : Array<Lesson>,
}
export interface UserProgress {
  'quizScores' : Array<[string, boolean]>,
  'completedLessons' : Array<string>,
}
export interface _SERVICE {
  'getModules' : ActorMethod<[], Array<Module>>,
  'getUserProgress' : ActorMethod<[], UserProgress>,
  'markLessonComplete' : ActorMethod<[string], undefined>,
  'resetProgress' : ActorMethod<[], undefined>,
  'submitQuizAnswer' : ActorMethod<[string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];